import { MD3DarkTheme, MD3LightTheme, type MD3Theme } from "react-native-paper";

export const materialLightTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 6,
  colors: {
    ...MD3LightTheme.colors,
    primary: "#10B981",
    onPrimary: "#FFFFFF",
    primaryContainer: "#D1FAE5",
    onPrimaryContainer: "#064E3B",
    secondary: "#4A6359",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#CCE8DB",
    onSecondaryContainer: "#062017",
    tertiary: "#3E6377",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#C2E8FF",
    onTertiaryContainer: "#001E2D",
    background: "#FFFFFF",
    onBackground: "#161D19",
    surface: "#FFFFFF",
    onSurface: "#161D19",
    surfaceVariant: "#F6F7F8",
    onSurfaceVariant: "#404944",
    outline: "#A7AFB6",
    outlineVariant: "#E2E6EA",
    error: "#A61B1B",
    onError: "#FFFFFF",
    errorContainer: "#FDE8E8",
    onErrorContainer: "#5B1A1A",
    elevation: {
      level0: "transparent",
      level1: "#FFFFFF",
      level2: "#FFFFFF",
      level3: "#FFFFFF",
      level4: "#FFFFFF",
      level5: "#FFFFFF",
    },
  },
};

export const materialDarkTheme: MD3Theme = {
  ...MD3DarkTheme,
  roundness: 6,
  colors: {
    ...MD3DarkTheme.colors,
    primary: "#34D399",
    onPrimary: "#052E26",
    primaryContainer: "#064E3B",
    onPrimaryContainer: "#D1FAE5",
    secondary: "#9CCDB8",
    onSecondary: "#133126",
    secondaryContainer: "#22473A",
    onSecondaryContainer: "#CCE8DB",
    tertiary: "#9FCBE2",
    onTertiary: "#073042",
    tertiaryContainer: "#234B5F",
    onTertiaryContainer: "#C2E8FF",
    background: "#0F1412",
    onBackground: "#E6F0EB",
    surface: "#151B18",
    onSurface: "#E6F0EB",
    surfaceVariant: "#24302A",
    onSurfaceVariant: "#BCC8C1",
    outline: "#88948E",
    outlineVariant: "#34403A",
    error: "#FFB4AB",
    onError: "#690005",
    errorContainer: "#93000A",
    onErrorContainer: "#FFDAD6",
    elevation: {
      level0: "transparent",
      level1: "#151B18",
      level2: "#1A221E",
      level3: "#1F2824",
      level4: "#222C27",
      level5: "#26302B",
    },
  },
};

export function getMaterialTheme(colorScheme: "light" | "dark" | null | undefined): MD3Theme {
  return colorScheme === "dark" ? materialDarkTheme : materialLightTheme;
}
