export const SUCCESS_MESSAGES = {
  login: "Sesion iniciada correctamente.",
  familiesRefreshed: "Familias actualizadas.",
  familyEntered: "Ingreso exitoso a la familia.",
  familyCreated: "Plantilla creada correctamente.",
  familyJoined: "Te uniste a la familia correctamente.",
  familyDeleted: "Plantilla eliminada correctamente.",
  memberUpdated: "Miembro actualizado correctamente.",
  memberDeleted: "Miembro eliminado correctamente.",
  memberCreated: "Miembro creado correctamente.",
  incomeUpdated: "Ingreso actualizado correctamente.",
  periodCreated: "Periodo creado correctamente.",
  pocketCreated: "Bolsa creada correctamente.",
  pocketUpdated: "Bolsa actualizada correctamente.",
  pocketDeleted: "Bolsa eliminada correctamente.",
  commitmentCreated: "Compromiso creado correctamente.",
  commitmentUpdated: "Compromiso actualizado correctamente.",
  commitmentDeleted: "Compromiso eliminado correctamente.",
  pocketBalanceCreated: "Saldo inicial registrado correctamente.",
  movementCreated: "Movimiento registrado correctamente.",
  initialIncomesSaved: "Ingresos iniciales guardados correctamente.",
  dashboardRefreshed: "Informacion actualizada.",
} as const;
